### ISSUE TITLE
Display bug for quarter and horizontal skins.

### ISSUE THREAD

**Issue by hoseinghasemi** [HanSolo/Medusa#49] opened 2016-12-14 11:08 UTC
There is a bug in quarter and horizontal gauges skin when the value is zero .
Node Direction is right to left .
![medusa bug](https://cloud.githubusercontent.com/assets/24562609/21179785/da077486-c20a-11e6-804d-29a778fec63d.png)

**Comment by HanSolo** [comment] 2016-12-14 12:35
What is the reason for you to set the node orientation from right to left?

**Comment by HanSolo** [comment] 2016-12-14 12:41
Now I always set the NodeOrientation for the gauge to LEFT_TO_RIGHT to make sure it works. It's already committed, so please let me know if it works for you.

**Comment by hoseinghasemi** [comment] 2016-12-14 14:09
Because in some languages like Persian, Arabic and maybe some other languages the orientation is right to left so we need to use right to left orientation.

**Comment by HanSolo** [comment] 2016-12-14 14:26
Ok, understand so like mentioned before I now always set the NodeOrientation for the gauge from LEFT_TO_RIGHT so please let me know it does work for you.

**Comment by hoseinghasemi** [comment] 2016-12-14 14:29
Sorry HanSolo. I check the gauges. The gauge orientation is left to right. The whole project is right to left but the gauges are left to right .
You are right the gauges should be left to right but the bug is remaining for zero values.
If the orientaion change to right to left the result is like this picture
![medusa bug 2](https://cloud.githubusercontent.com/assets/24562609/21185643/c7e06a12-c226-11e6-8b64-c992969b64c1.png)

**Comment by HanSolo** [comment] 2016-12-14 14:31
Ok, could you please provide the code that you used to create that effect so that I can reproduce it here?

**Comment by HanSolo** [comment] 2016-12-18 06:48
If you would like me to have a closer look into your problem, please provide some sample code that makes it possible to reproduce it, otherwise I will close this issue!

**Closed** 2016-12-21 09:20 UTC
Labels: wontfix
